image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  SERVICE: proj-semestre-1

build:
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

    - export TEST_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - export RELEASE_IMAGE=$CI_REGISTRY_IMAGE:latest
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build -t $TEST_IMAGE --cache-from $RELEASE_IMAGE .
    - docker push $TEST_IMAGE

release:
  stage: release
  tags:
    - docker
  only:
    - tags
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export TEST_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - export RELEASE_IMAGE=$CI_REGISTRY_IMAGE:latest
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

deploy:
  stage: deploy
  tags:
    - docker
  only:
    - tags
  variables:
    GIT_STRATEGY: none
  script:
    - 'wget --header "webhook-token: $token" $host/hooks/deploy'
