__all__ = [
    "avatar",
    "login",
    "profile",
    "chats",
    "admin",
    "index",
    "navette",
    "commande",
    "recherche_users",
    "nouvelleAmplet",
    "nouvelleNavette",
    "amplets_en_cours",
    "inscription_amplet",
    "send_inscription_amplet",
    "succes",
    "accepter_participation",
    "refuser_participation"
]